server:
  port: 8015
spring:
  application:
    name: zuul

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    lease-expiration-duration-in-seconds: 20
    #实例使用ip代替hostName
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 10
    instance-info-replication-interval-seconds: 20
    initial-instance-info-replication-interval-seconds: 30
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://eureka0:8000/eureka/,http://eureka1:8001/eureka/,http://eureka2:8002/eureka/

#zuul.Servlet30WrapperFilter.pre.disable: true
#zuul.FormBodyWrapperFilter.pre.disable: true
zuul.DebugFilter.pre.disable: true

zuul.RibbonRoutingFilter.route.disable: true
zuul.SimpleHostRoutingFilter.route.disable: true
zuul.SendForwardFilter.route.disable: true


ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 5000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  #刷新服务端服务器列表频率，默认 30*1000
  ServerListRefreshInterval: 2000


#hystrix.command.default.execution.timeout.enabled=false
#超时时间（默认1000，单位：ms）
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
#线程池核心线程数，默认为10
hystrix.threadpool.default.coreSize: 100

customZuul:
  separate-thread-pool-keys: user

hystrix.threadpool.user.coreSize: 50

hystrix.threadpool.user.maxQueueSize: 100
hystrix.threadpool.user.queueSizeRejectionThreshold: 100