spring:
  application:
    name: eureka

server:
  port: 8001

eureka:
  instance:
     appname: ${spring.application.name}
     hostname: peer1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer2:8002/eureka/
      

