spring:
  application:
    name: eureka
server:
  port: 8000

eureka:
  instance:
    appname: ${spring.application.name}
    hostname: eureka0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka/,http://eureka2:8002/eureka/
      

