spring:
  application:
    name: eureka

server:
  port: 8002

eureka:
  instance:
    appname: ${spring.application.name}
    hostname: peer2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:8001/eureka/
      

