server:
  port: 8010
spring:
  application:
    name: user

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 2
    lease-expiration-duration-in-seconds: 4
    #实例使用ip代替hostName
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 2
    instance-info-replication-interval-seconds: 4
    initial-instance-info-replication-interval-seconds: 4
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/
      #defaultZone: http://eureka0:8000/eureka/,http://eureka1:8001/eureka/,http://eureka2:8002/eureka/

